# Generated by Django 5.2.6 on 2025-09-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='tipo',
        ),
    ]
